services:
  mysql:
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306

  adminer:
    ports:
      - ${ADMINER_PUBLISH_PORT}:8080

  redis:
    ports:
      - ${REDIS_PUBLISH_PORT}:6379

  rabbitmq:
    ports:
      - ${RABBITMQ_PUBLISH_PORT}:15672
